SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
FPS = 60

WORLD_WIDTH = 1280
WORLD_HEIGHT = 720

RANDOM_SEED = 42

STARTING_WORKERS = 2
STARTING_WARRIORS = 0
STARTING_FOOD_SOURCES = 7
STARTING_RESOURCE_SOURCES = 4
STARTING_THREATS = 0
STARTING_FOOD_STORAGE = 10

COLONY_TARGET_ANTS = 100
FOOD_COST_PER_EGG = 5
EGG_HATCH_TICKS = 300
ANT_FOOD_CONSUMPTION_TICKS = 2500
FOOD_DISCOVERY_RADIUS = 36
EXPLORATION_STEP_DISTANCE = 180
EXPLORATION_RECALL_TICKS = 1800
MAX_SIMULATION_TICKS = 120000

NEST_X = SCREEN_WIDTH // 2
NEST_Y = SCREEN_HEIGHT // 2
NEST_RADIUS = 60

QUEEN_RADIUS = 12
WORKER_RADIUS = 4
WARRIOR_RADIUS = 6
FOOD_SIZE = 14
RESOURCE_SIZE = 12
THREAT_RADIUS = 9
