SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
FPS = 60

WORLD_WIDTH = 1280
WORLD_HEIGHT = 720

RANDOM_SEED = 42

STARTING_WORKERS = 20
STARTING_WARRIORS = 5
STARTING_FOOD_SOURCES = 3
STARTING_RESOURCE_SOURCES = 4
STARTING_THREATS = 2

NEST_X = SCREEN_WIDTH // 2
NEST_Y = SCREEN_HEIGHT // 2
NEST_RADIUS = 60

QUEEN_RADIUS = 12
WORKER_RADIUS = 4
WARRIOR_RADIUS = 6
FOOD_SIZE = 14
RESOURCE_SIZE = 12
THREAT_RADIUS = 9
